import { posts } from '@/data/site'

/** The generic branded card — carries the home route and any unknown path. */
export const OG_DEFAULT = '/og.png'

const slugs = new Set(posts.map((p) => p.slug))
const routeCards: Record<string, string> = {
  '/work': '/og/work.png',
  '/writing': '/og/writing.png',
  '/about': '/og/about.png',
}

/**
 * The single path→share-card mapping, shared by the runtime head (usePageMeta)
 * and the build-time prerender (scripts/prerender.ts). Cards are generated by
 * `npm run og` (scripts/gen-og.mjs) and committed to public/og/; the prerender
 * asserts every mapped card exists in dist. Unknown paths → the generic card.
 */
export function ogImageForPath(pathname: string): string {
  const m = pathname.match(/^\/writing\/([^/]+)\/?$/)
  if (m && slugs.has(m[1])) return `/og/${m[1]}.png`
  return routeCards[pathname.replace(/\/$/, '') || '/'] ?? OG_DEFAULT
}

/** og:image:alt text — one format everywhere (runtime + prerender). */
export function ogAltForTitle(title?: string): string {
  return title ? `${title} — Nathan Gupta` : 'Nathan Gupta — Cognitive Neuroscientist at AWA'
}
